### ISSUE TITLE
timeout parameter setting

### ISSUE THREAD

**Issue by qianqianpang** [OMH4ck/Squirrel#5]
Dear developers,

I'm very interested in your research work. 
During my attempt to reproduce the SQLite tests using Squirrel, I conducted a 24-hour test and found that the number of bugs was zero, with the remaining issues being hangs due to timeouts. This result differs from your findings. Could you please help me understand this experimental outcome?
If I want to identify bugs, is it possible to achieve this by increasing the timeout parameter, and how can I modify the timeout parameters in the project files? I look forward to your response and greatly appreciate your assistance.

Sincerely, Cherrypang

**Comment by Changochen** [comment]
Could you provide the steps you run your experiments and the screenshot during its running?

**Comment by qianqianpang** [comment]
Certainly, thank you for your response. 
Here are the steps I followed and some screenshots of the tests I ran. 
![image](https://github.com/OMH4ck/Squirrel/assets/77775690/48a4ae0d-04ce-445e-a11f-a618c7a8764f)

Due to time constraints, I only conducted tests for 5 hours.
![image](https://github.com/OMH4ck/Squirrel/assets/77775690/61a33b7d-8c65-4e92-a78d-21b0a2b278d2)

**Comment by Changochen** [comment]
Thanks for the details. Your results looks normal.

The dockerfile is testing the latest version of `SQLite`, which I think lots of people have been testing it with `Squirrel`. Therefore, you cannot find new bugs in short time.

If you want to reproduce the bugs mentioned in our paper, you can modify the dockerfile to checkout an older version of sqlite once it is cloned.

If you want to find new bugs, you can try to provide new seeds instead of the ones used by `Squirrel`, as it has been well tested.

**Comment by qianqianpang** [comment]
Okay
I want to know if I can discover more potential bugs by increasing the timeout parameter?

**Comment by Changochen** [comment]
In theory, increasing the timeout parameter allows you to find bugs that requires long triggering time, but it degrades the fuzzing performance. One thing you can do is running through the timeout testcases manually, to see whether it actually crashes SQLite.

**Comment by qianqianpang** [comment]
Okay, thank you very much.
